# name: CI

# on:
#   push:
#     branches: [ develop, feature/* ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#     - uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'

#     - run: pip install --upgrade pip
#     - run: pip install -r requirements.txt

#     - run: pip install flake8
#     - run: flake8 app.py --max-line-length=90
name: CI

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: pip install flake8 pytest

    - name: Run linting
      run: flake8 helper.py --max-line-length=90

    - name: Run unit tests
      run: pytest -v
